add script for comparing audio framemd5
amiaopensource/ffmprovisr pull request #173
Opened 2017-04-15 21:08 UTC by privatezero

Was linking to the script for comparing video framemd5s, made some tweaks so that it will work for audio comparison.

Also, is it worth explicitly noting in the explanation that ffmpeg by default converts the input to 16 bit when it generates the framemd5s, so the hashes are for that value and not the actual content of the input file?

2017-04-15 23:13 UTC, ablwr commented
LGTM but maybe someone with more area expertise should review.

2017-04-15 23:20 UTC, privatezero commented on check_audio_framemd5.sh
> +sample_rate=$(grep -v '^#' ${input_hash} | head -n 1 | tr -d ' ' | cut -d',' -f4)
the main change is in setting and unsetting this variable, and then to the ffmpeg command

2017-04-15 23:34 UTC, dericed commented on check_audio_framemd5.sh
> +    md5_tmp=""${USERPROFILE}/$(basename ${input_hash}).tmp""
quadruple quotes?!

2017-04-15 23:35 UTC, dericed commented on check_audio_framemd5.sh
> +sample_rate=$(grep -v '^#' ${input_hash} | head -n 1 | tr -d ' ' | cut -d',' -f4)
should put $input_hash in quotes throughout, else when you run `check_audio_framemd5.sh -m " ; find ~/Music -name *.mp3 -delete"` you might be sad.

2017-04-16 00:09 UTC, privatezero commented on check_audio_framemd5.sh
> +    md5_tmp=""${USERPROFILE}/$(basename ${input_hash}).tmp""
No idea! Could it have something to do with how Cygwin works?

2017-04-16 00:09 UTC, privatezero commented on check_audio_framemd5.sh
> +sample_rate=$(grep -v '^#' ${input_hash} | head -n 1 | tr -d ' ' | cut -d',' -f4)
hahahaha ooh yeah good point! I'll take a look at this and the other script that is on ffmprovisr and make that change.

2017-04-16 04:42 UTC, retokromer commented on check_audio_framemd5.sh
> +  Website: https://github.com/amiaopensource/ffmprovisr/blob/gh-pages/check_framemd5.sh
URL should read check_audio_framemd5.sh

2017-04-16 04:44 UTC, retokromer commented on check_audio_framemd5.sh
> +    md5_tmp=""${USERPROFILE}/$(basename ${input_hash}).tmp""
It’s double quote for Cygwin, not quadruple.

2017-04-16 04:50 UTC, retokromer commented on index.html
> +          <p>You may verify an MD5 checksum file created this way by using a <a href="check_audio_framemd5.sh" target="_blank">Bash script</a>.</p>
Good catch!

2017-04-16 04:58 UTC, retokromer commented on check_audio_framemd5.sh
> +$(ffmpeg -i ${input_file} -loglevel 0 -filter_complex "asetnsamples=n='$sample_rate'" -f framemd5 -vn ${md5_tmp})
`-filter:a` should fit, instead of `-filter_complex`.

2017-04-16 05:02 UTC, retokromer requested changes

2017-04-16 05:02 UTC, retokromer commented on check_audio_framemd5.sh
> +sample_rate=$(grep -v '^#' ${input_hash} | head -n 1 | tr -d ' ' | cut -d',' -f4)
If I remember carefully, the other script don’t need the extraction of metadata.

I suggest that we change the existing script in `check_video_framemd5.sh` that checks video only, and add a new `check_framemd5.sh` that checks both video and audio.

2017-04-16 14:49 UTC, retokromer requested changes
Please update the date of `check_video_framemd5.sh`:
`VERSION='2017-04-16'`

2017-04-16 14:50 UTC, retokromer approved these changes

2017-04-16 14:55 UTC, retokromer approved these changes

2017-04-16 14:55 UTC, retokromer commented
Thank you!

2017-04-16 14:56 UTC, merged