Added command for splitting into segments (segment muxer).
amiaopensource/ffmprovisr pull request #189
Opened 2017-05-17 16:55 UTC by pjotrek-b

The title says it all :grin: 
Put it right next to "join/concatenate". Thought that makes sense.

2017-05-17 17:01 UTC, retokromer requested changes
Stylistic nitpicking… LGTM!

2017-05-17 17:01 UTC, retokromer commented on index.html
> +            <dt>-c copy</dt><dd>use stream copy mode to re-mux instead of re-encode.</dd>
When you end the sentence with a period, you should start it with a capital.

2017-05-17 17:01 UTC, retokromer commented on index.html
> +            <dt>-f segment</dt><dd>use <a href="http://www.ffmpeg.org/ffmpeg-formats.html#toc-segment_002c-stream_005fsegment_002c-ssegment">segment muxer</a> for generating the output.</dd>
same

2017-05-17 17:01 UTC, retokromer commented on index.html
> +            path, name and extension of the output file.<br />
please use `<br>` (aka HTML 5, instead of XHTML)

2017-05-17 17:01 UTC, retokromer commented on index.html
> +            In this example, '%03d' means: 3-digits, zero-padded<br />
same

2017-05-17 19:44 UTC, pjotrek-b commented on index.html
> +            In this example, '%03d' means: 3-digits, zero-padded<br />
Roger that.
Got used to XHTML syntax, cause before HTML5 <br/> caused problems in some engines...
Will fix it as you proposed :smile:

2017-05-17 19:48 UTC, retokromer commented on index.html
> +            In this example, '%03d' means: 3-digits, zero-padded<br />
Thank you! I also personally prefer XHTML, but in practice HTML5 is currently _the_ standard. We moved `ffmprovisr` some months ago.

2017-05-18 08:28 UTC, pjotrek-b commented
Fixed the requested changes, one typo and improved printf-digit syntax examples.

2017-05-18 08:29 UTC, retokromer approved these changes

2017-05-18 08:30 UTC, retokromer commented
Thank you very much indeed!

2017-05-18 08:30 UTC, merged

2017-05-18 09:26 UTC, pjotrek-b commented
Thanks! :)

One final question about this:
The segment muxer allows to create a segment-list file that can be used 1:1 for the concat muxer.

Didn't want to bloat the text, but any suggestion/idea where this information might fit in?
(or if it makes sense to mention it at all?)

2017-05-18 09:35 UTC, retokromer commented
I guess it makes sense for our audience (as long as I know it… ;-)